---
apiVersion: v1
kind: Namespace
metadata:
  name: dnsutils
  labels:
    name: dnsutils
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: dnsutils
spec:
  containers:
  - name: dnsutils
    image: 192.168.13.206:5000/dnsutils:1.0.0
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
