# dnsutils container with Ubuntu 24.04

# docker build -t dnsutils:1.0.0 .
# docker run --rm -d --name dnsutils --hostname=dnsutils --env TZ='EAST+5EDT,M3.2.0/2,M11.1.0/2' --env TIMEZONE='America/New_York' dnsutils:1.0.0
# docker exec -it dnsutils dig -v
# docker rm -f dnsutils

FROM ubuntu:24.04

LABEL org.opencontainers.image.authors="DDN <daniel@isociel.com>"
LABEL version="1.00"
LABEL Description="Lightweight container with tools to troubleshoot DNS in K8s"

# Install utilities
RUN apt update && apt -y upgrade && apt install -y dnsutils vim

# Clean up.
RUN apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
ENTRYPOINT ["/bin/sh", "-c", "tail -f /dev/null"]
